#!/usr/bin/env fish

if test (id -u) -eq 0
	echo "This script should not be run as root"
	exit 1
end

set dotfiles_repository "https://github.com/tednaaa/dotfiles"


sudo pacman -Syu --noconfirm


if not command -s rustup
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
end
if not command -s mise
	curl https://mise.run | sh
end


if not command -s paru
	sudo pacman -S --noconfirm --needed base-devel git
	git clone https://aur.archlinux.org/paru.git
	cd paru
	makepkg -si --noconfirm --needed
end

if not test -d ~/dotfiles
	git clone $dotfiles_repository ~/dotfiles
end

paru -S --noconfirm --needed symm
symm unlink
symm link


set packages

set cli_tools alacritty wezterm neovim starship btop ripgrep zoxide eza fd bat yazi fzf jq openbsd-netcat rsync cmake
set packages $packages $cli_tools

set fonts ttf-jetbrains-mono-nerd ttf-font-awesome
set packages $packages $fonts

set desktop hyprland hyprpaper hyprlock hyprshot xdg-desktop-portal-hyprland brightnessctl waybar mako rofi-wayland nwg-look
set packages $packages $desktop

set apps ueberzugpp mpv clipse bluetui dolphin pavucontrol 7zip obs-studio
set packages $packages $apps

paru -S --noconfirm --needed $packages
