#!/bin/fish

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'

dotfiles_repository="https://github.com/tednaaa/dotfiles"

print_success() {
	echo -e "${GREEN}✓ $1${NC}"
}
print_warning() {
	echo -e "${YELLOW}⚠ $1${NC}"
}
print_error() {
	echo -e "${RED}✗ $1${NC}"
	exit 1
}

if test (id -u) -eq 0
	print_error "This script should not be run as root"


sudo pacman -Syu --noconfirm

if not type -q paru
	sudo pacman -S --needed --noconfirm base-devel git
	git clone https://aur.archlinux.org/paru.git
	cd paru
	makepkg -si

if not test -d ~/dotfiles
	git clone $dotfiles_repository ~/dotfiles

paru -S --noconfirm --needed symm
symm unlink
symm link


set packages

packages=(
	"alacritty"
	"wezterm"
	"neovim"
	"starship"
	"btop"

	"ripgrep"
	"zoxide"
	"eza"
	"fd"
	"bat"
	"yazi"
	"fzf"
	"jq"

	"openbsd-netcat"
	"rsync"
	"cmake"

	"ttf-jetbrains-mono-nerd"
	"ttf-font-awesome"
)

for package in "${packages[@]}"; do
	if pacman -Q "$package" &> /dev/null; then
		print_skip "$package is already installed"
	else
		echo "Installing $package..."
		sudo pacman -S --noconfirm "$package" || yay -S --noconfirm "$package"
	fi
done
print_success "Basic toolset installation complete"

print_step "Installing hyprland"
hyprland_packages=(
	"hyprland"
	"hyprpaper"
	"hyprlock"
	"hyprshot"
	"xdg-desktop-portal-hyprland"

	"brightnessctl"
	"waybar"
	"mako" # notifications
	"rofi-wayland" # app launcher
	"nwg-look" # for dark theme
	"ueberzugpp" # image rendering support in alacritty
	"mpv" # video player
	"clipse"
	"bluetui"
	# "impala" # waiting for https://github.com/pythops/impala/issues/24

	"dolphin"
	"pavucontrol"
	"7zip"
	"obs-studio"
)

for package in "${hyprland_packages[@]}"; do
	if pacman -Q "$package" &> /dev/null; then
		print_skip "$package is already installed"
	else
		echo "Installing $package..."
		sudo pacman -S --noconfirm "$package"
	fi
done
print_success "Hyprland installation complete"
