[symlinks]
"hypr" = ".config/hypr"
"waybar" = ".config/waybar"
"rofi" = ".config/rofi"
"yazi" = ".config/yazi"
"satty" = ".config/satty"

# "theme/gtk-3.0/settings.ini" = ".config/gtk-3.0/settings.ini"
# "theme/gtk-4.0/settings.ini" = ".config/gtk-4.0/settings.ini"
# "theme/qt/kdeglobals" = ".config/kdeglobals"
# "theme/qt/qt5ct.conf" = ".config/qt5ct/qt5ct.conf"
# "theme/qt/qt6ct.conf" = ".config/qt6ct/qt6ct.conf"

"alacritty" = ".config/alacritty"
"zellij" = ".config/zellij"
"wezterm" = ".config/wezterm"
"ghostty" = ".config/ghostty"

"zed" = ".config/zed"
"nvim" = ".config/nvim"

"lazygit" = ".config/lazygit"
"lazydocker" = ".config/lazydocker"
"mise" = ".config/mise"

"fish/config.fish" = ".config/fish/config.fish"
"fish/functions" = ".config/fish/functions"
"fish/conf.d" = ".config/fish/conf.d"

"git/.gitconfig" = ".gitconfig"
"npm/.npmrc" = ".npmrc"

[packages]
ignored = [
	"base", "base-devel", "linux", "linux-firmware", "efibootmgr", "intel-ucode",
	"btrfs-progs", "snapper", "grub", "grub-btrfs", "zram-generator",
	"bluez", "bluez-utils", "networkmanager", "libpulse", "sof-firmware",
	"pipewire", "pipewire-alsa", "pipewire-jack", "pipewire-pulse", "gst-plugin-pipewire", "wireplumber",
	"paru", "paru-debug", "paru-bin", "yay-bin", "symm", "downgrade",
	"qemu-desktop", "virt-manager", "dnsmasq",
	"steam", "elyprismlauncher", "dbeaver", "spotify-launcher"
]

playwright_workaround = ["enchant"]
lsp = ["gitlab-ci-ls"]


fonts = ["noto-fonts", "noto-fonts-cjk", "noto-fonts-emoji", "ttf-jetbrains-mono-nerd"]
nvidia = ["nvidia", "nvidia-utils"]

apps = ["firefox", "google-chrome", "obs-studio", "telegram-desktop"]

terminal = [
  "alacritty", "zellij", "neovim", "fish", "starship", "fastfetch", "man-db",
	"tabiew", "btop",
	"yazi", "ueberzugpp", "resvg",
  "fzf", "jq", "ripgrep", "zoxide", "eza", "fd", "bat", "unzip",
  "git", "git-delta", "lazygit",
  "openbsd-netcat", "openssh", "rsync", "bind", "cmake", "postgresql",
	"docker", "docker-buildx", "docker-compose", "lazydocker",
	"kubectl", "kustomize", "helm", "k9s", "doctl", "glab", "ansible", "opentofu", "fluxcd"
]

desktop_hyprland = [
	"ly", "hyprland", "hyprpaper", "hyprlock",
	"xdg-desktop-portal-hyprland", "xdg-desktop-portal-gtk",
	"brightnessctl", "waybar", "swaync", "rofi", "power-profiles-daemon",
	"dolphin", "pavucontrol", "7zip", "mpv", "bluetui", "satty", "grim", "slurp",
	"clipse", "wl-clipboard", "wl-clip-persist",
	"orchis-theme", "papirus-icon-theme", "apple_cursor"
]
