[mgr]
show_hidden = true

[opener]
tabiew = [
	{ run = 'tw "$@"', block = true, desc = "Open with tabiew" },
]

[open]
prepend_rules = [
	{ name = "*.csv", use = "tabiew" },
	{ name = "*.xlsx", use = "tabiew" },
	{ name = "*.xls", use = "tabiew" },
	{ mime = "text/csv", use = "tabiew" },
	{ mime = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", use = "tabiew" },
]
